//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSwift.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCustomer", ReplyAction="http://tempuri.org/IService1/CreateCustomerResponse")]
        void CreateCustomer(string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress, string CreditCardNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        void DeleteCustomer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomer", ReplyAction="http://tempuri.org/IService1/UpdateCustomerResponse")]
        void UpdateCustomer(string username, string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress, string CreditCardNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCustomer", ReplyAction="http://tempuri.org/IService1/SearchCustomerResponse")]
        string SearchCustomer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListCustomers", ReplyAction="http://tempuri.org/IService1/ListCustomersResponse")]
        string ListCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListPremium", ReplyAction="http://tempuri.org/IService1/ListPremiumResponse")]
        string ListPremium();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListPolicy", ReplyAction="http://tempuri.org/IService1/ListPolicyResponse")]
        string ListPolicy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Logout", ReplyAction="http://tempuri.org/IService1/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePremium", ReplyAction="http://tempuri.org/IService1/CreatePremiumResponse")]
        void CreatePremium(string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePremium", ReplyAction="http://tempuri.org/IService1/DeletePremiumResponse")]
        void DeletePremium(string policyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePremium", ReplyAction="http://tempuri.org/IService1/UpdatePremiumResponse")]
        void UpdatePremium(string PremiumID, string carID, string policyID, string description, string cost, string dateMade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchPremium", ReplyAction="http://tempuri.org/IService1/SearchPremiumResponse")]
        string SearchPremium(string policyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidateName", ReplyAction="http://tempuri.org/IService1/ValidateNameResponse")]
        bool ValidateName(out string error, int minLength, int maxLength, string InputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidateNumber", ReplyAction="http://tempuri.org/IService1/ValidateNumberResponse")]
        bool ValidateNumber(out string error, int minLength, int maxLength, string InputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidatePassword", ReplyAction="http://tempuri.org/IService1/ValidatePasswordResponse")]
        bool ValidatePassword(out string error, int minLength, int maxLength, string InputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidateAddress", ReplyAction="http://tempuri.org/IService1/ValidateAddressResponse")]
        bool ValidateAddress(out string error, int minLength, int maxLength, string InputString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebSwift.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebSwift.ServiceReference1.IService1>, WebSwift.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateCustomer(string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress, string CreditCardNum) {
            base.Channel.CreateCustomer(firstName, lastName, password, Address, PhoneNumber, EmailAddress, CreditCardNum);
        }
        
        public void DeleteCustomer(string username) {
            base.Channel.DeleteCustomer(username);
        }
        
        public void UpdateCustomer(string username, string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress, string CreditCardNum) {
            base.Channel.UpdateCustomer(username, firstName, lastName, password, Address, PhoneNumber, EmailAddress, CreditCardNum);
        }
        
        public string SearchCustomer(string username) {
            return base.Channel.SearchCustomer(username);
        }
        
        public string ListCustomers() {
            return base.Channel.ListCustomers();
        }
        
        public string ListPremium() {
            return base.Channel.ListPremium();
        }
        
        public string ListPolicy() {
            return base.Channel.ListPolicy();
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public void CreatePremium(string firstName, string lastName, string password, string Address, string PhoneNumber, string EmailAddress) {
            base.Channel.CreatePremium(firstName, lastName, password, Address, PhoneNumber, EmailAddress);
        }
        
        public void DeletePremium(string policyID) {
            base.Channel.DeletePremium(policyID);
        }
        
        public void UpdatePremium(string PremiumID, string carID, string policyID, string description, string cost, string dateMade) {
            base.Channel.UpdatePremium(PremiumID, carID, policyID, description, cost, dateMade);
        }
        
        public string SearchPremium(string policyID) {
            return base.Channel.SearchPremium(policyID);
        }
        
        public bool ValidateName(out string error, int minLength, int maxLength, string InputString) {
            return base.Channel.ValidateName(out error, minLength, maxLength, InputString);
        }
        
        public bool ValidateNumber(out string error, int minLength, int maxLength, string InputString) {
            return base.Channel.ValidateNumber(out error, minLength, maxLength, InputString);
        }
        
        public bool ValidatePassword(out string error, int minLength, int maxLength, string InputString) {
            return base.Channel.ValidatePassword(out error, minLength, maxLength, InputString);
        }
        
        public bool ValidateAddress(out string error, int minLength, int maxLength, string InputString) {
            return base.Channel.ValidateAddress(out error, minLength, maxLength, InputString);
        }
    }
}
